name: Continuous Integration Pipeline

on:
  push:
    branches: [ "master", "homol", "development" ]
  pull_request:
    branches: [ "master", "homol", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore src/LedgerLiteUsersAPI/LedgerLiteUsersAPI.slnx

    - name: Build
      run: dotnet build src/LedgerLiteUsersAPI/LedgerLiteUsersAPI.slnx --no-restore --configuration Release

    - name: Test
      run: dotnet test src/LedgerLiteUsersAPI/LedgerLiteUsersAPI.slnx --no-build --configuration Release --verbosity normal

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)#